import "../styles/globals.css";
import type { AppProps } from "next/app";
import ContextProvider from "../context";
import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import Header from "components/header";
import { SnackbarProvider } from "notistack";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <>
      <Head>
        <title>Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.imgur.com/L8Ege78.png" />
      </Head>
      <ContextProvider>
        <SnackbarProvider maxSnack={3}>
          <SessionProvider session={session}>
            <Header>Planner</Header>
            <Component {...pageProps} />
          </SessionProvider>
        </SnackbarProvider>
      </ContextProvider>
    </>
  );
}
